const state={data:null,view:"daily"};
const $=s=>document.querySelector(s);const b64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));const fmt=new Intl.NumberFormat("zh-CN",{maximumFractionDigits:2});
const esc=v=>String(v??"—").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function decrypt(password){const p=await fetch("encrypted-data.json",{cache:"no-store"}).then(r=>{if(!r.ok)throw Error();return r.json()});const base=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveKey"]);const key=await crypto.subtle.deriveKey({name:"PBKDF2",salt:b64(p.salt),iterations:p.iterations,hash:"SHA-256"},base,{name:"AES-GCM",length:256},false,["decrypt"]);const clear=await crypto.subtle.decrypt({name:"AES-GCM",iv:b64(p.iv)},key,b64(p.ciphertext));return JSON.parse(new TextDecoder().decode(clear))}
const columns={
 daily:[["rank","排名"],["code","代码"],["name","名称"],["score","总分"],["price","价格"],["pct_change","当日涨跌"],["return_60d","60日涨跌"],["return_ytd","年内涨跌"],["pe_ttm","PE"],["pb","PB"],["amount","成交额"],["trend_score","趋势"],["value_score","估值"],["risk_score","低风险"]],
 etfs:[["code","代码"],["name","名称"],["region","市场"],["signal","信号"],["score","总分"],["price","价格"],["premium","溢价率"],["amount","成交额"],["mom63","63日动量"],["mom126","126日动量"]],
 stocks:[["code","代码"],["name","名称"],["signal","信号"],["score","总分"],["quality_score","质量"],["value_score","估值"],["pe","PE"],["pb","PB"],["roe","ROE"],["mom126","126日动量"],["buy_state","买点判断"]]
};
function percent(v,scale=1){return v==null?"—":`${fmt.format(Number(v)*scale)}%`}function money(v){return v==null?"—":Number(v)>=1e8?`${fmt.format(Number(v)/1e8)}亿`:fmt.format(v)}
function cell(key,v){if(v==null||v==="")return"—";if(["pct_change","return_60d","return_ytd"].includes(key))return percent(v);if(["premium","mom63","mom126"].includes(key))return percent(v,100);if(key==="amount")return money(v);return esc(typeof v==="number"?fmt.format(v):v)}
function dailyRows(){if(state.view==="history"){const d=$("#history-date").value;return(state.data.stockHistory?.[d]?.top100||[]).map((r,i)=>({...r,rank:i+1}))}return(state.data.dailyMarket?.top100||[]).map((r,i)=>({...r,rank:i+1}))}
function rowsForView(){if(["daily","history"].includes(state.view))return dailyRows();return state.data[state.view]||[]}
function renderSummary(){const d=state.view==="history"?state.data.stockHistory?.[$("#history-date").value]:state.data.dailyMarket;if(!["daily","history"].includes(state.view)||!d){$("#summary").innerHTML="";return}const t=d.tests||{};$("#summary").innerHTML=`<article><span>行情日期</span><strong>${esc(d.date)}</strong></article><article><span>全市场覆盖</span><strong>${fmt.format(d.universe_count)}</strong></article><article><span>通过硬过滤</span><strong>${fmt.format(d.eligible_count)}</strong></article><article><span>前100稳定度</span><strong>${percent(t.weight_perturbation_top100_overlap,100)}</strong></article><article><span>模型版本</span><strong>${esc(d.model_version)}</strong></article>`}
function renderTable(){const q=$("#search").value.trim().toLowerCase();const rows=rowsForView().filter(r=>!q||`${r.code} ${r.name}`.toLowerCase().includes(q));const cols=columns[["daily","history"].includes(state.view)?"daily":state.view]||[];$("#thead").innerHTML=`<tr>${cols.map(([,x])=>`<th>${x}</th>`).join("")}</tr>`;$("#tbody").innerHTML=rows.map(r=>`<tr>${cols.map(([k])=>`<td class="${k==="score"?"score":""}">${cell(k,r[k])}</td>`).join("")}</tr>`).join("");$("#count").textContent=`显示 ${rows.length} 条`;$("#table-wrap").hidden=!rows.length;$("#empty").hidden=!!rows.length;if(!rows.length)$("#empty").textContent=state.view==="daily"?"全市场日更任务尚未生成首个交易日榜单。":"该视图暂无数据。";renderSummary()}
function renderValidation(){const v=state.data.validation||{};const e=v.enhanced;const o=e?.oos_metrics||v.oos_metrics;$("#validation-panel").innerHTML=o?`<div class="validation-grid"><article><span>样本外年化</span><strong>${percent(o.cagr,100)}</strong></article><article><span>最大回撤</span><strong>${percent(o.max_drawdown,100)}</strong></article><article><span>夏普</span><strong>${fmt.format(o.sharpe)}</strong></article><article><span>样本外月份</span><strong>${o.months}</strong></article></div><div class="validation-copy"><h2>全市场模型测试口径</h2><p>每日扫描会验证覆盖数量、重复代码、评分边界、排序一致性，并用两组小幅权重扰动检验前100重合率。历史榜单从自动任务启用日开始积累，不能替代多年无幸存者偏差的历史回测。</p></div>`:"暂无验证数据"}
function setView(view){state.view=view;document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.view===view));const validation=view==="validation";$("#toolbar").hidden=validation;$("#table-wrap").hidden=validation;$("#empty").hidden=true;$("#validation-panel").hidden=!validation;$("#summary").hidden=validation;$("#history-date").hidden=view!=="history";if(validation)renderValidation();else renderTable()}
$("#unlock-form").addEventListener("submit",async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;button.textContent="解密中…";try{state.data=await decrypt($("#password").value);$("#password").value="";$("#lock").hidden=true;$("#dashboard").hidden=false;$("#updated").textContent=`模型数据更新时间：${state.data.updatedAt||"—"}`;const dates=Object.keys(state.data.stockHistory||{}).sort().reverse();$("#history-date").innerHTML=dates.map(d=>`<option>${d}</option>`).join("");setView(state.data.dailyMarket?"daily":"etfs")}catch{$("#error").textContent="密码错误，或加密数据加载失败。"}finally{button.disabled=false;button.textContent="解锁"}});
$("#lock-button").addEventListener("click",()=>location.reload());document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>setView(b.dataset.view)));$("#search").addEventListener("input",renderTable);$("#history-date").addEventListener("change",renderTable);
